name: SimSent
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.6
  - faiss-cpu=1.5.1
  - pip>=19.1.1
  - pip:
    - numpy
    - tensorflow
    - tensorflow_hub
    - ipykernel
    - jupyter
    - jupyterlab
    - sqlitedict
    - requests
